# Generated by Django 4.1.2 on 2022-12-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='img',
            new_name='data',
        ),
    ]
