# Generated by Django 4.1.2 on 2022-10-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('new', 'новая заявка'), ('pending', 'заявка рассматривается'), ('accepted', 'данные приняты'), ('rejected', 'данные не приняты')], default=('new', 'новая заявка'), max_length=50),
        ),
    ]
