# Generated by Django 4.1.2 on 2022-12-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_img_images_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('new', 'новая заявка'), ('pending', 'заявка рассматривается'), ('accepted', 'данные приняты'), ('rejected', 'данные не приняты')], default='new', max_length=50),
        ),
    ]
