# Generated by Django 4.1.2 on 2022-10-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_perevaladded_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coords',
            table='pereval_coords',
        ),
        migrations.AlterModelTable(
            name='images',
            table='pereval_images',
        ),
    ]
